--dirty reads
use S9
--PROBLEM: SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
SELECT * FROM Copii
WAITFOR DELAY '00:00:15'
SELECT * FROM Copii
COMMIT TRAN


-- SOLUTION: SET TRANSACTION ISOLATION LEVEL TO READ COMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Copii
WAITFOR DELAY '00:00:15'
SELECT * FROM Copii
COMMIT TRAN