--dirty reads
use Biblioteca
--PROBLEM: SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
BEGIN TRAN
SELECT * FROM Carti
WAITFOR DELAY '00:00:15'
SELECT * FROM Carti
COMMIT TRAN


-- SOLUTION: SET TRANSACTION ISOLATION LEVEL TO READ COMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Carti
WAITFOR DELAY '00:00:15'
SELECT * FROM Carti
COMMIT TRAN
