-- nonrepeatable reads
use Biblioteca
--PROBLEM: SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Carti
WAITFOR DELAY '00:00:15'
SELECT * FROM Carti
COMMIT TRAN


-- SOLUTION: SET TRANSACTION ISOLATION LEVEL TO REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Carti
WAITFOR DELAY '00:00:15'
SELECT * FROM Carti
COMMIT TRAN