-- phantom reads
use Biblioteca
-- PROBLEM: SET TRANSACTION ISOLATION LEVEL TO REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Carti
WAITFOR DELAY '00:00:15'
SELECT * FROM Carti
COMMIT TRAN


-- SOLUTION: SET TRANSACTION ISOLATION LEVEL TO SERIALIZABLE
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM Carti
WAITFOR DELAY '00:00:15'
SELECT * FROM Carti
COMMIT TRAN